#!/bin/zsh
#
# http://github.com/mitchweaver/bin
#
# wal with a gif and set the gif as wallpaper with xwinwrap and mpv
#

[ -f "$1" ] || exit 1

pkill -9 xwinwrap

wal -i "$1" -o ~/scripts/post_wal

WEBM="$1"+".webm"

xwinwrap -ni -b -fs -ov -nf -- mpv --wid WID --no-config --keepaspect=no --loop --no-border --vd-lavc-fast --x11-bypass-compositor=no --gapless-audio=yes --hwdec=auto --really-quiet --name=mpvbg "$1" &
#$xwin $mpv "$WEBM" &
